import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';
import 'package:fix_flow_a_i/main.dart';
import 'package:firebase_core/firebase_core.dart';
// If you have firebase_options.dart generated by FlutterFire CLI, import it:
import 'package:fix_flow_a_i/firebase_options.dart';

void main() {
  setUpAll(() async {
    TestWidgetsFlutterBinding.ensureInitialized();
    // Use this if you have firebase_options.dart:
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    // If you don’t have firebase_options.dart, you can use:
    // await Firebase.initializeApp();
  });

  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());

    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}
